### ISSUE TITLE
aria-api looks at placeholder

### ISSUE THREAD

**Issue by jribbens** [xi/aria-api#6]
`getName()` on an `input` element will return the `placeholder` content, which does not appear to be behaviour specified by Accessible Name and Description Computation 1.1 or draft 1.2 as far as I can tell (although it is what Chrome does).

**Comment by xi** [comment]
Unfortunately the standards are not very clear on this. Accname 1.2 (draft) has this to say:

> Otherwise, if the current node's native markup provides an attribute (e.g. alt) or element (e.g. HTML label or SVG title) that defines a text alternative, return that alternative in the form of a flat string as defined by the host language, unless the element is marked as presentational (role="presentation" or role="none").
>
> See HTML-AAM, SVG-AAM, or other host language documentation for more information on markup that defines a text alternative.

HTML-AAM does not provide an explicit list. It does mention [`placeholder` as a possible text alternative for input elements](https://www.w3.org/TR/html-aam-1.0/#input-type-text-input-type-password-input-type-search-input-type-tel-input-type-email-input-type-url-and-textarea-element-accessible-name-computation).

Do you have more information on the current behavior of browsers and ATs? If there is no clear consensus I would prefer to wait until the standards improve.

**Comment by jribbens** [comment]
It looks like Firefox and Edge also look at `placeholder` so I think your response is reasonable.
